version: '3.9'
services:
  src: 
    build: ./src
    container_name: react_c
    ports: 
      - '3000:3000'
    volumes:
      - ./src:/app
      - ./app/node_modules
    stdin_open: true
    tty: true